version: '3.8'
services:
  php-environment:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: curso_poo_svr
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql
    container_name: curso_poo_db
    ports: 
        - 9906:3306
    restart: always
    environment:
        MYSQL_USER: aula_oo
        MYSQL_PASSWORD: aulaotop
        MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: curso_poo_phpmyadmin
    ports:
        - 8088:80
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db